---
deployment:
  tasks:
    - export DEPLOYPATH=/home/asatryan101/public_html  # Add /<app_folder> if required
    - /bin/cp index.html $DEPLOYPATH                 #Copy specific file to destination from root
    - /bin/cp /fpv/index.html $DEPLOYPATH   #copy specific file from source sub folder
    - /bin cp * $DEPLOYPATH                           #copy all from root
    - /bin cp /fpv/* $DEPLOYPATH             #copy all from sub folder root
    - /bin/cp -r * $DEPLOYPATH                        #copy all recursively to $DEPLOYPATH
